(setq mac-option-modifier 'meta)
  (setq mac-command-modifier 'super)

  ;; Keybonds
  (global-set-key [(super a)] 'mark-whole-buffer)
  (global-set-key [(super v)] 'yank)
  (global-set-key [(super c)] 'kill-ring-save)
  (global-set-key [(super s)] 'save-buffer)
  (global-set-key [(super l)] 'goto-line)
  (global-set-key [(super z)] 'undo)
  (global-set-key [(super w)] 'delete-frame)
  (global-set-key [(super x)] 'kill-region)
  (global-set-key [(super z)] 'undo)
  (global-set-key [(super +)] 'text-scale-adjust)
  (global-set-key [(super =)] 'text-scale-adjust)
  (global-set-key [(super -)] 'text-scale-adjust)
  (global-set-key (kbd "s-0") 'text-scale-adjust)
