(defun myHS ()
  (hs-minor-mode)
  (local-set-key [return] 'newline-and-indent)
  (setq mslk-hs-key (make-keymap))	;定义映射表
  (local-set-key (kbd "C-c j") mslk-hs-key)
  (define-key mslk-hs-key (kbd "M-h") 'hs-hide-all)
  (define-key mslk-hs-key (kbd "M-s") 'hs-show-all)
  (define-key mslk-hs-key (kbd "C-h")  'hs-hide-block)
  (define-key mslk-hs-key (kbd "C-s")  'hs-show-block))

(add-hook 'c-mode-common-hook 'myHS)
(add-hook 'c++-mode-hook 'myHS)
(add-hook 'scheme-mode-hook 'myHS)
(add-hook 'emacs-lisp-mode-hook 'myHS)
(add-hook 'java-mode-hook 'myHS)
(add-hook 'cperl-mode-hook 'myHS)
(add-hook 'slime-mode-hook 'myHS)
