(defun rope-extract-variable (var-name)
  (interactive "svar-name:")
  (save-buffer)
  (when (region-active-p)
    (let* ((project (projectile-project-root))
	   (file (file-relative-name (buffer-file-name) project))
	   (start (- (region-beginning) 1))
	   (end (- (region-end) 1))
	   (cmd (format "~/.emacs.d/bin/rope_extract_variable.py %s %s %s %s %s" project file start end var-name))
	   (default-directory project)
	   (proc (start-process-shell-command "reop extract" "*rope extract*" cmd))
	   (sentinel (lambda (proc state)
		       (let ((exit-code (process-exit-status proc)))
			 (if (eq 0 exit-code)
			     (progn
			       (message "rope extract variable success.")
			       (revert-buffer-with-fine-grain t t)
			       (when (featurep 'diff-hl)
				 (message "ok for diff-hl?")
				 (diff-hl-update))
			   (error "rope extract variable fail. see *rope extract* for get detail"))))))
      (set-process-sentinel proc sentinel))))
